### ISSUE TITLE
Issue in the code

### ISSUE THREAD

**Issue by Anshkarnwal** [ZainRk/FitClub-Starter#16]
Hi there, I noticed that the code in the repository you mentioned doesn't seem to match exactly what was shown in the YouTube video {https://www.youtube.com/watch?v=gpqoZQ8GNK8&list=PLTCB5XiVO7CIXrdogeMitGwLguYjW_zWc&index=5&t=59s}. I tried to run the code in Visual Studio Code and shared the results in the image attached. I appreciate it if you could review this issue.

![Capture](https://github.com/ZainRk/FitClub-Starter/assets/112880360/6e400ee1-deb7-4932-b45b-46642dab9d34)

**Comment by Surajbhatt03** [comment]
So should i use this code to work on it ?

**Comment by ZainRk** [comment]
Hi, this repo is the starter pack of this tutorial as mentioned in the video.
You will find the assets, directory setup and package.json here. Thanks.
